server:
  port: 8000

spring:
  profiles:
    active: dev

# MyBatis配置
mybatis-plus:
  # Mapper映射文件的位置
  mapper-locations: classpath:mapper/*.xml
  # 包下所有类的别名，配置别名为了在对象映射文件中接收参数类型和返回参数类型时省略包路径
  type-aliases-package: com.daniellin07.bookshop.module.system.domain

# 七牛云
qiniu:
  # 文件大小 /M
  max-size: 5

# 验证码有效时间/分钟
code:
  expiration: 5