# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&useSSL=false&useAffectedRows=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

# Jwt配置
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 2个小时
  expiration: 7200000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true